### ISSUE TITLE
ngx-videogular vg-time-display not working with Angular 14

### ISSUE THREAD

**Issue by tuanbs** [videogular/ngx-videogular#100]
Hi here,
I've just upgraded Angular from v13 to v14 and found out the `vg-time-display` not working. Any idea or workaround? Thanks in advance.

**Comment by JohnRachid** [comment]
We are having this issue as well. Would appreciate a workaround.

**Comment by IxquitilisSaid** [comment]
Could you please elaborate on your issue? I'm going to publish v6.0.0 in a couple of minutes with the upgrade to Angular 14, maybe that fixes it?

**Comment by JohnRachid** [comment]
Updating to v6.0.0 seems to have fixed it. Thanks, @IxquitilisSaid! This can probably be closed.
