### ISSUE TITLE
Scrub bar sometimes not reliable on iOS

### ISSUE THREAD

**Issue by KyleSmith0905** [videogular/ngx-videogular#101]
### Description
When swiping along the scrub bar quickly, the scrub bar visibly moves but reverts back to the original position when letting go. I tested this on a touch-screen Windows and it responded perfectly, so maybe some cross-browser compatibility issues are happening.

Model Name: iPhone 11
Software Version: 15.5

### Expected Behavior
When quickly touch-swiping along the scrub bar, the scrub bar should be in the same position from where your finger lifted.

### Actual Behavior
The scrub bar goes back to the position it was at before swiping.

### Steps to Reproduce
  1. Visit the [ngxVideogular demo website](https://videogular.github.io/ngx-videogular/) on mobile iOS.
  2. Scroll down to the demo video on that page.
  3. Try swiping quickly along the scrollbar.

**Comment by KyleSmith0905** [comment]
https://github.com/videogular/ngx-videogular/blob/master/libs/ngx-videogular/controls/src/lib/components/vg-scrub-bar/vg-scrub-bar.component.ts#L151-L155 It seems like removing these 4 lines stops it from stuttering, I am also concerned if it will behave differently, but I'm not noticing any changes from removing those 4 lines. I'll submit a PR once I pass/alter the tests.

**Comment by IxquitilisSaid** [comment]
Will be live with the v14 update. Thanks for the contribution! 😄
