### ISSUE TITLE
onPlayerReady type was VgAPI and now is any

### ISSUE THREAD

**Issue by C0ZEN** [videogular/ngx-videogular#11]
So I followed the comments about taking the lead here with this new project.
That is nice but can you can tell me why does the types have changed?

**Example before:**
```
onPlayerReady: EventEmitter<VgApi>;
```

**Example after:**
```
onPlayerReady: EventEmitter<any>;
```

Is it on purpose?
If so, why?

**Comment by IxquitilisSaid** [comment]
Hm... Good question.
I just checked the git history of it and apparently it was always set to `any` (last change to it was 4 years ago).

But I'm adding it either way, nice catch

**Comment by IxquitilisSaid** [comment]
Fixed: https://github.com/videogular/ngx-videogular/commit/5d741fe6f7625366239823910c4431a37a6cce8e

**Comment by C0ZEN** [comment]
@IxquitilisSaid seems a bit strange 4 years...
I mean I have no idea then where I came from with this type but it seems good though so thank you for the fix.
Also VgApi is now VgApiService right?

**Comment by IxquitilisSaid** [comment]
Yes sir! 
All components, directives and services (except VgImaAds, I forgot about that one but fixing it on next release) are now suffixed with their corresponding type.

Currently working on updating the docs properly and writing a migration guide from `videogular2`

**Comment by C0ZEN** [comment]
@IxquitilisSaid I am wondering then why sometimes you keep the Vg prefix but it was removed from the modules and my guess is that this was done by you right?

**Comment by IxquitilisSaid** [comment]
Yup, that was me.
Well, on the first rewrite I made it a monorepo so the modules would be separate packages. There I kept the Vg prefix on the exported modules.

But when I moved to secondary entry points, I decided to drop the prefix on the Modules and keep it on Components, Directives and Services.
In hindsight, I should probably add the prefix again just to save everyone the headache of substituting the old names.

But yeah, one of those "coding at 4AM" type of things. What you reckon, though? Keep it as it is or add the Vg back to the Modules?

**Comment by C0ZEN** [comment]
@IxquitilisSaid from my opinion/experience using a prefix for projects used as dependencies for other projects should always be prefixed whenever it is possible.
This leverage the easy to use/easy to read kind of scenarios due to the prefix.
During development or during code review you can easily understand where the code is coming from and it is clearly a painkiller on huge projects with a bunch of dependencies.
Also this avoid any kind of conflicts during imports minimizing the potential errors and the harassment of choosing where to import from.
The only drawback of doing it is the potential longer element names but it's fucking two more letters we should not even care about this but haters will hate you know.

So yeah if this was my call I definitely would add a prefix everywhere.

**Comment by C0ZEN** [comment]
Also if you have the time and courage you could create schematic to minimize a breaking change in this particular case.

**Comment by IxquitilisSaid** [comment]
`but it's fucking two more letters` => You don't get it, we're in 70's. Every byte needs to be optimized and budgeted 🤣 

Yeah, I thought about adding schematics but was wondering if it was worth the hassle... Still, if your feedback had monetary value, it would be platinum! Going to add the prefix again.

Hopefully today I'll release v2.0 with all this stuff inside

**Comment by C0ZEN** [comment]
@IxquitilisSaid platinum *noice*
Honestly this kind of stuff is not a hurry at all so even if doing a schematic is time consuming I think that we should as developers target the value and this solution is clearly appropriate so it should be done.
I have the knowledge about schematics but I had never created one before and hell even if a am well busy I kind of want to help you on this one.
Let me handle it please - the rename of modules and creating a schematics -.
I will try to provide a PR sunday.
Sounds good to you?

**Comment by IxquitilisSaid** [comment]
![fast draw](https://media.giphy.com/media/TGJ5PMG7tYGLBkvyeU/giphy.gif)

Way ahead of you, buddy-o. Already renamed them 😎 
But if you want to do the schematics, all the power to ya! Take your time and I'll be glad to smash that merge button

**Comment by C0ZEN** [comment]
@IxquitilisSaid did you planned or did you already released the breaking change with the prefix on modules?

**Comment by IxquitilisSaid** [comment]
It's live on v2.0.0

**Comment by C0ZEN** [comment]
@IxquitilisSaid yeah I figured out that you will probably ship asap this.
Meaning bringing a schematic almost pointless.
What's done is done though.
