### ISSUE TITLE
How to use ngx-videogular for Angular 13?

### ISSUE THREAD

**Issue by ranjitpowar88** [videogular/ngx-videogular#115]
How to use ngx-videogular for Angular 13?

I have tried installing it. But getting error in compiling project.

**Comment by salesh** [comment]
@ranjitpowar88 use previous release https://github.com/videogular/ngx-videogular/tree/v5.0.1 5.0.1

**Comment by ranjitpowar88** [comment]
> @ranjitpowar88 use previous release https://github.com/videogular/ngx-videogular/tree/v5.0.1 5.0.1

But how do I install previous version? If execute 
npm install @videogular/ngx-videogular  
Then latest version installing?

**Comment by salesh** [comment]
```
npm install [package-name]@[version-number]
```

```
npm install @videogular/ngx-videogular@5.0.1

**Comment by Th-Barth** [comment]
Hello,
I had to leave my Ionic/Angular App-Project (using ngx-videogular) in October last year for another project as is. The video player worked in my app. In the meantime I had to reinstall windows, switched to windows 11 and I had to set up my dev environment. Everything seems to be up to date now:

# ng version
Angular CLI: 15.1.5
Node: 18.14.0
Package Manager: npm 9.3.1
OS: win32 x64

# npm list
├── @types/core-js@2.5.5
├──[...]
├── @videogular/ngx-videogular@7.0.1

But I also get the error: 
error TS2740: Type 'HTMLVideoElement' is missing the following properties from type 'IMediaElement': audioTracks, msAudioCategory, msAudioDeviceType, msPlayToDisabled, and 10 more.

17     <video [vgMedia]="media" #media id="singleVideo" preload="auto" controls>

I integrated the video as described in the [Getting Started](https://videogular.github.io/ngx-videogular/docs/getting-started/)

Do I still have to use an older videogular version? Which version? Or is there another solution in the meantime?

**Comment by Th-Barth** [comment]
Hello again, which angular version do I need for @videogular/ngx-videogular@7.0.1 ?
