### ISSUE TITLE
Add a migration guide from Videogular2 to Ngx-Videogular

### ISSUE THREAD

**Issue by IxquitilisSaid** [videogular/ngx-videogular#12]

**Comment by mamzellejuu** [comment]
I tested it today, you just have to uninstall the videogular2 dependencies and install the second one, seems seamless

**Comment by stephencawood** [comment]
How's this migration guide coming? I'm trying to figure out how to get it working on my own in Angular 10 but I could use some help. The migration guide would be great--even the simplest of examples would be useful.
I have a video playing, but I still get this error:  `error NG8001: 'vg-player' is not a known element`
Thanks!

**Comment by IxquitilisSaid** [comment]
@stephencawood pushed 😎

**Comment by IxquitilisSaid** [comment]
Published https://github.com/videogular/ngx-videogular/blob/master/docs/ngx-videogular-demo/migrating-from-videogular2/README.md

Closing issue
