### ISSUE TITLE
Uncaught TypeError: Cannot read properties of undefined (reading 'call')

### ISSUE THREAD

**Issue by ngs2020** [videogular/ngx-videogular#124]
### Description
*Describe the issue or new feature.*

### Expected Behavior
*If this is an issue, document the expected behavior.  If this is a feature, delete this block.*

### Actual Behavior
*If this is an issue, describe the actual behavior.  If this is a feature, delete this block.*

### Steps to Reproduce
*If this is an issue, describe the steps you took to see the issue. If this is a feature, delete this block.*
  1. Step 1
  2. Step 2

### Attachments
*Try to include screenshots for bugs or design assets for enhancements*

| **Image Title** |
| --- |
| (https://media.giphy.com/media/143vPc6b08locw/giphy.gif) |
| Image description |

**Comment by ngs2020** [comment]
hi , I have been working on a project that recieves and plays videos. when i run the project on localhost, everything is ok . but when I build and run it on real server, I encounter this error in the console and displaying fails.

**Comment by ngs2020** [comment]
<img width="1421" alt="Screenshot 1401-10-05 at 11 37 03" src="https://user-images.githubusercontent.com/59912698/209805345-11662112-ae5b-412b-b539-cf9b096d7aa6.png">

**Comment by frenzymind** [comment]
Same here. I can run in production if add these properties:
```
              "buildOptimizer": false,
              "optimization": false,
```
but then bundle size become bigger.
For the same time if I create new project and add player with hls - it works. I don't know what the difference, angular v14.
