### ISSUE TITLE
Fullscreen API does not return a Promise as per the specification

### ISSUE THREAD

**Issue by jansgescheit** [videogular/ngx-videogular#146]
### Description
According to the [Fullscreen API specification](https://fullscreen.spec.whatwg.org/#ref-for-dom-document-exitfullscreen%E2%91%A0), both `requestFullscreen()` and `exitFullscreen()` methods should return a Promise. However, in the Videogular library, this behavior is not implemented in the `VgFullscreenApiService`. The methods are called without returning any Promise.

### Expected Behavior
The `toggleFullscreen()`, `request()` and `exit()` methods should return a Promise that resolves when the operation completes.

### Actual Behavior
The `toggleFullscreen()`, `request()` and `exit()` methods do not return a Promise. This can cause issues with handling fullscreen transitions properly, especially when chaining operations or handling errors.

### Attachments
- Fullscreen API Specification: [Fullscreen API](https://fullscreen.spec.whatwg.org/#ref-for-dom-document-exitfullscreen%E2%91%A0)
- Videogular Library Code: [VgFullscreenApiService](https://github.com/videogular/ngx-videogular/blob/master/libs/ngx-videogular/core/src/lib/services/vg-fullscreen-api/vg-fullscreen-api.service.ts)

**Code Snippet from VgFullscreenApiService:**
```typescript
enterElementInFullScreen(elem: any) {
  elem[this.polyfill.request]();
}

exit() {
  this.isFullscreen = false;
  this.onChangeFullscreen.emit(false);

  // Exit from native fullscreen
  if (this.isAvailable && this.nativeFullscreen) {
    document[this.polyfill.exit]();
  }
}
```

**Comment by IxquitilisSaid** [comment]
Good catch, I'll get it merged and deployed.
Thanks for contributing! 😄
