### ISSUE TITLE
Please add documentation page

### ISSUE THREAD

**Issue by armanhadifatah** [videogular/ngx-videogular#16]
There is no documentation page please add one

**Comment by johnpankowicz** [comment]
@armanhadifatah  Until that is written, you can go here: 
https://github.com/videogular/ngx-videogular/blob/master/docs/ngx-videogular-demo/getting-started/README.md

**Comment by IxquitilisSaid** [comment]
Moved to `In Progress` while adding the GitHub pages deploy

**Comment by IxquitilisSaid** [comment]
Deployed to https://videogular.github.io/ngx-videogular/
Have a great day and thank you for using our project! 😄
