### ISSUE TITLE
Production ready?

### ISSUE THREAD

**Issue by shanehsu** [videogular/ngx-videogular#19]
Without proper documentation, it's a bit hard to judge if this form of videogular is complete or if it is production-ready. 

I understand that it is a huge undertaking to take videogular to Angular 9 and beyond. Kudos!

**Comment by IxquitilisSaid** [comment]
Yes. All features and the overall code is the same as videogular2.
So if you used and trusted it before, you can expect the same thing.

The "missing docs" only refer to the GitHubPages docs, which are in here as https://github.com/videogular/ngx-videogular/tree/master/docs/ngx-videogular-demo (I already updated the name changes and whatnot)

**Comment by IxquitilisSaid** [comment]
https://videogular.github.io/ngx-videogular/ works now 😄  (my bad, been swapped with work)
I'm pushing the updated README links in a sec
