### ISSUE TITLE
Migration Page 404

### ISSUE THREAD

**Issue by mokipedia** [videogular/ngx-videogular#20]
### Description
*Describe the issue or new feature.*
The Github Pages linked here produce a 404.

### Expected Behavior
To see the sure to be wonderfully detailed and easy-to-follow migration page.

### Actual Behavior
404

### Steps to Reproduce
open https://videogular.github.io/ngx-videogular/docs/migrating-from-videogular/

**Comment by IxquitilisSaid** [comment]
Related to #33 
Referencing it to keep them synced
