### ISSUE TITLE
Question: Dashjs v3 support?

### ISSUE THREAD

**Issue by tiberiumihai** [videogular/ngx-videogular#29]
### Description
Does ngx-videogular support dashjs v3?

### Expected Behavior
dashjs v3 is supported.

### Actual Behavior
dashjs v2 is supported.

**Comment by IxquitilisSaid** [comment]
So, after #26 got merged we kinda backed ourselves into the "drop DashJS 2.X.X support and move to 3.X.X" corner (oversight by me).
#30 is going in the same direction so the question now is if we want to keep going as it is (only support 3.X.X) or just add checks around all deprecated methods as to support both (also update docs regarding that).

@Elecash could you give your 2 cents regarding this?

**Comment by Elecash** [comment]
I would provide support only for Dash v3 since it is the most recent version and it probably has backward compatibility to any Dash format.

If someone wants Dash v2 support they should stick with older versions of `ngx-videogular` in my opinion.

**Comment by IxquitilisSaid** [comment]
Aye aye then!

**Comment by tiberiumihai** [comment]
I agree. I’ll close this one since I already use dashjs@3.1.3.
