### ISSUE TITLE
Update the imports and examples

### ISSUE THREAD

**Issue by jsgoupil** [videogular/ngx-videogular#33]
### Description
All the imports and examples point to the old videogular2. Please update the example, stackblitz, etc.
If you can't update the documentation, consider updating the README.md to explain what has to be done to include the module properly.

**Comment by IxquitilisSaid** [comment]
I'm actually in the process of updating the GitBook so links like ['https://videogular.github.io/videogular2/docs', 'https://videogular.github.io/videogular2-showroom'] become ['https://videogular.github.io/ngx-videogular/docs', 'https://videogular.github.io/ngx-videogular-showroom'] and include the updated docs.

But good thing you brought up the Stackblitz part, if not I would probably forget to do it 😅
Thanks for bringing it up and have a great day! 😄
