### ISSUE TITLE
How can I define the language of the "skip ad" button

### ISSUE THREAD

**Issue by bfis108137** [videogular/ngx-videogular#42]
### Description
I am not able to define the language for the "skip ad" button

### Expected Behavior
I would expect a way to be able to do this by either of the two methods provided by the google sdk.

1.) https://developers.google.com/interactive-media-ads/docs/sdks/html5/client-side/localization
2.) https://developers.google.com/interactive-media-ads/docs/sdks/html5/client-side/faq#13

### Actual Behavior
I was not able to define the language.

### Steps to Reproduce
1.) Create a sample app as found in the repo
2.) Try to change the language

**Comment by IxquitilisSaid** [comment]
Once we publish v3.0.0 (should be before the 14th of January), you'll be able to add `[vgSkipButtonLocale]="'LANG_CODE'"` to the `vg-ima-ads` component
