### ISSUE TITLE
Setting a thumbnail?

### ISSUE THREAD

**Issue by jer-tx** [videogular/ngx-videogular#48]
### Description
I'd like to set a thumbnail that appears on the video player

### Expected Behavior
I'd assume some <vg> element could help facilitate that (maybe `<vg-overlay-play>`?) but I don't see anything in documentation

**Comment by IxquitilisSaid** [comment]
Add a `poster` attribute to your HTML video tag and pass the URL of the image.
It won't affect the `<vg-overlay-play>` button
