### ISSUE TITLE
angular 12 compatibility

### ISSUE THREAD

**Issue by pasblin** [videogular/ngx-videogular#60]
### Description
*Describe the issue or new feature.*

### Expected Behavior
*If this is an issue, document the expected behavior.  If this is a feature, delete this block.*

### Actual Behavior
*If this is an issue, describe the actual behavior.  If this is a feature, delete this block.*

### Steps to Reproduce
*If this is an issue, describe the steps you took to see the issue. If this is a feature, delete this block.*
  1. Step 1
  2. Step 2

### Attachments
*Try to include screenshots for bugs or design assets for enhancements*

| **Image Title** |
| --- |
| (https://media.giphy.com/media/143vPc6b08locw/giphy.gif) |
| Image description |

**Comment by IxquitilisSaid** [comment]
Shipped!
