### ISSUE TITLE
Type 'HTMLVideoElement' is missing the following properties from type 'IMediaElement'

### ISSUE THREAD

**Issue by dooziiinc** [videogular/ngx-videogular#66]
### Description
installed  "@videogular/ngx-videogular": "^4.0.0",

Added  to app.module.ts:
```
import { VgBufferingModule } from '@videogular/ngx-videogular/buffering';
import { VgControlsModule } from '@videogular/ngx-videogular/controls';
import { VgCoreModule } from '@videogular/ngx-videogular/core';
import { VgOverlayPlayModule } from '@videogular/ngx-videogular/overlay-play';
```

Created new component containing the following code from the example:

```
<vg-player>
        <video [vgMedia]="media" #media id="singleVideo" preload="auto" controls>
            <source src="http://static.videogular.com/assets/videos/videogular.mp4" type="video/mp4">
        </video>
    </vg-player>
```
and to my video.component.ts:

`import { VgApiService } from '@videogular/ngx-videogular/core';`

### Expected Behavior
Expected video to play or the project to compile

### Actual Behavior
Received compile error:   
Type 'HTMLVideoElement' is missing the following properties from type 'IMediaElement': audioTracks, msAudioCategory, msAudioDeviceType, msGraphicsTrustStatus, and 13 more.

### Steps to Reproduce
ng build

### Attachments
*Try to include screenshots for bugs or design assets for enhancements*

| **Image Title** |
| --- |
| (https://media.giphy.com/media/143vPc6b08locw/giphy.gif) |
| Image description |

**Comment by dooziiinc** [comment]
NOTE: 
Found an old post on a different bug report and ended up adding 
[vgMedia]="$any(media)"
and the project compiles.

**Comment by akaustel** [comment]
Would be nice to get this fixed. That said, this workaround is working just fine.

**Comment by WuglyakBolgoink** [comment]
still exists with v6.0.0

**Comment by Sbef98** [comment]
Still having such problem in v8.0.0
