### ISSUE TITLE
Fullscreen mode on Ipad doesn't work

### ISSUE THREAD

**Issue by IhorKobylinskiy** [videogular/ngx-videogular#67]
### Description
When I click on the toggle fullscreen icon on Ipad the fullscreen does not enable - only the fullscreen icon changes

### Expected Behavior
Clicking on the fullscreen icon `<vg-fullscreen></vg-fullscreen>` should toggle fullscreen mode on the Ipad

### Actual Behavior
Clicking on the fullscreen icon `<vg-fullscreen></vg-fullscreen>` doesn't toggle fullscreen mode on the Ipad

### Steps to Reproduce
1. Run ionic application with ngx video player on the Ipad
2. Try to enable fullscreen mode

### Attachments
*Try to include screenshots for bugs or design assets for enhancements*

**Comment by IhorKobylinskiy** [comment]
<img width="466" alt="Screen Shot 2021-08-03 at 10 59 32 AM" src="https://user-images.githubusercontent.com/7584176/127980115-8ea97eb1-ec31-4f70-a765-a19689a138ea.png">
<img width="462" alt="Screen Shot 2021-08-03 at 10 59 40 AM" src="https://user-images.githubusercontent.com/7584176/127980124-d6d5e2b6-28fa-4e74-9d64-c31173e657aa.png">

**Comment by IxquitilisSaid** [comment]
Afternoon! 

I'll look into it but could you please give me some extra info?
- Which browser are you currently testing it on (the one in the screenshots)?
- Does that also happen on a different one?

**Comment by IhorKobylinskiy** [comment]
@IxquitilisSaid, Hello. Thanks for the reply. This is an ionic application I get this issue on the IPad and IPad simulator. In Safari on IPad fullscreen works properly. I have traced `videogular-ngx-videogular-core.js` and it seems the reason is that `VgUtilsService.isiOSDevice()` doesn't work properly in case of ionic application on IPad

**Comment by IhorKobylinskiy** [comment]
<img width="1103" alt="Screen Shot 2021-08-03 at 4 45 40 PM" src="https://user-images.githubusercontent.com/7584176/128026472-71b1002d-0233-4c70-9d90-c23a58d7d0a2.png">

**Comment by IhorKobylinskiy** [comment]
Here is the discussion about how to detect is it IPad - https://stackoverflow.com/questions/57776001/how-to-detect-ipad-pro-as-ipad-using-javascript

**Comment by IxquitilisSaid** [comment]
v4.1.0 is out!
