### ISSUE TITLE
Error executing ionic build --prod with ionic5 + Angular12.1.1 

### ISSUE THREAD

**Issue by newzdhong** [videogular/ngx-videogular#70]
Error: src/app/share/videogular2-player/videogular2-player.component.html:20:11 - error TS2740: Type 'HTMLVideoElement' is missing the following properties from type 'IMediaElement': audioTracks, msAudioCategory, msAudioDeviceType, msGraphicsTrustStatus, and 13 more.

<video [vgMedia]="media"

**Comment by IxquitilisSaid** [comment]
Sorry for the late reply.
Please use it as so `[vgMedia]="$any(media)"`.

**Comment by newzdhong** [comment]
thank you!
