### ISSUE TITLE
error on angular 12.2.4 with videogular version 4.1.0

### ISSUE THREAD

**Issue by pasblin** [videogular/ngx-videogular#72]
### Description
Cant compile project because this errors:

- Cannot find name 'MSGraphicsTrust'.
-  Cannot find name 'MSMediaKeys'.

### Expected Behavior
*If this is an issue, document the expected behavior.  If this is a feature, delete this block.*

### Actual Behavior
*If this is an issue, describe the actual behavior.  If this is a feature, delete this block.*

### Steps to Reproduce
*If this is an issue, describe the steps you took to see the issue. If this is a feature, delete this block.*
  1. Step 1
  2. Step 2

### Attachments
*Try to include screenshots for bugs or design assets for enhancements*

| **Image Title** |
| --- |
| (https://media.giphy.com/media/143vPc6b08locw/giphy.gif) |
| Image description |

**Comment by igorlino** [comment]
@pasblin any reason why you closed the issue ?  I seem to see similar problem

**Comment by NetMajom** [comment]
> @pasblin any reason why you closed the issue ? I have seem to see similar problem and was wondering how it can be solved, after the angular upgrade.

After upgrading Angular 13 this problem exists again. My workaround is to set `"skipLibCheck": true` in tsconfig, I know it's not a good solution, but till the next update this will help. 

For now, the newest version for ngx-videogular is `4.2.0`

Waiting for the update...
