### ISSUE TITLE
Not working with angular 13

### ISSUE THREAD

**Issue by abhiramriet** [videogular/ngx-videogular#74]
### Description
Error in lib at compiling. Because of removed interfaces in type script.

### Expected Behavior
*If this is an issue, document the expected behavior.  If this is a feature, delete this block.*

### Actual Behavior
*If this is an issue, describe the actual behavior.  If this is a feature, delete this block.*

### Steps to Reproduce
*If this is an issue, describe the steps you took to see the issue. If this is a feature, delete this block.*
  1. Step 1
  2. Step 2

### Attachments
*Try to include screenshots for bugs or design assets for enhancements*

| **Image Title** |
| --- |
| (https://media.giphy.com/media/143vPc6b08locw/giphy.gif) |
| Image description |

**Comment by Wenrong108** [comment]
I got these errors in ng13

![image](https://user-images.githubusercontent.com/57497730/141069670-c67e2cb3-203e-4236-9f4a-85c301a64f33.png)

**Comment by IxquitilisSaid** [comment]
v5.0.0 is published!

**Comment by abhiramriet** [comment]
Tried with v5.0.0 still having issues loading the player.
![Screenshot 2021-11-10 210727](https://user-images.githubusercontent.com/3153108/141144857-12f4cfe1-d62c-490e-bdc4-1c2ba63237f3.png)

**Comment by IxquitilisSaid** [comment]
Fixed on v5.0.1
