### ISSUE TITLE
ngx-videogular not working with Angular 13

### ISSUE THREAD

**Issue by zornic84** [videogular/ngx-videogular#76]
Good morning,

I want to upgrade from Angular12 to Angular13, but I get the following error message when running "npm update":

npm ERR! Could not resolve dependency:
npm ERR! peer @angular/common@">=8.0.0 <13.0.0" from @videogular/ngx-videogular@5.0.0
npm ERR! node_modules/@videogular/ngx-videogular
npm ERR!   @videogular/ngx-videogular@"^5.0.0" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.

**Comment by IxquitilisSaid** [comment]
Fixed on v5.0.1. Thanks for pointing it out! 😄

**Comment by akshatrana02** [comment]
using v5.0.1 getting error 
Cannot read properties of undefined (reading 'subscriptions')
    at VgControlsComponent.onPlayerReady (videogular-ngx-videogular-controls.mjs:38:45)
    at videogular-ngx-videogular-controls.mjs:33:84
