### ISSUE TITLE
Dash streaming on IOS Safari throwing MediaPlayer not initialized! error

### ISSUE THREAD

**Issue by nolafs** [videogular/ngx-videogular#87]
### Description
IOS Safari issue with Dash. Player is throwing "MediaPlayer not initialized!". It does not prevent the video being played back but when the player is reset, router navigation will throw the same error and stop the routing.

### Expected Behavior
Destroying the player should not prevent the routing of the application.

### Actual Behavior
It should not prevent the routing.

**Comment by tm3610** [comment]
Hi,
Same problem with IOS Mobile,
Please update.
